# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [24]:
N = 10
array = np.arange(N)[::-1]
array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [33]:
N = 10
array_ = np.arange(N + 1)[::-1]
diag = np.eye(N + 1) * array_
print(sum(sum(diag)))    # Correct result only for diagonal matrix

55.0


In [34]:
# For general type of matrix
sum_diag = 0
for i in range(N + 1):
    sum_diag += diag[i][i]
print(sum_diag)

55.0


# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [26]:
a = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]    
    ])

b = np.array([4, 12, -3])

In [27]:
from numpy import linalg

In [30]:
# Solution
c = linalg.solve(a, b)
c 

array([ 0.46666667,  3.84444444, -5.55555556])

In [31]:
# Check
np.dot(a, c)

array([ 4., 12., -3.])